export {default as arrowLeftIcon } from './arrowLeftIcon.svg'
export {default as arrowRightIcon } from './arrowRightIcon.svg'
export {default as pancakesWapIcon } from './pancakeSwapIcon.svg'
export {default as aaveIcon } from './aave.svg'
export {default as uniswapIcon } from './uniswap.svg'
export {default as compoundIcon } from './compound.svg'
export {default as metaMaskIcon } from './metamask.svg'

export {default as raydiumIcon } from './raydium.svg'
export {default as trustWalletIcon } from './trustWalletIcon.svg'
export {default as oneInchIcon } from './oneInch.svg'
export {default as venusIcon } from './venus.svg'
export {default as infuraIcon } from './infura.svg'
export {default as quicknodeIcon } from './quicknode.svg'
export {default as balancerIcon } from './balancer.svg'
export {default as closeTagOrangeIcon } from './top-left-card-orange.svg'
export {default as closeTagIcon } from './top-left-card.svg'

export {default as bitcoinIcon } from './bitcoin.svg'
export {default as etheriumIcon } from './etherium1.svg'
export {default as cosmosIcon } from './cosmos.svg'
export {default as fantomIcon } from './fantom.svg'
export {default as avalancheIcon } from './avalanche.svg'
export {default as polkadotIcon } from './polkadot.svg'
export {default as atomIcon } from './atom.svg'
export {default as tronIcon } from './tron.svg'
export {default as polygonIcon } from './polygon.svg'
export {default as arbitrumIcon } from './arbitrum.svg'
export {default as solanaIcon } from './solana.svg'
export {default as binanceSCIcon } from './binanceSC.svg'
export {default as cardanoIcon } from './cardano.svg'

export {default as solidityIcon } from './solidity.svg'
export {default as tsIcon } from './ts.svg'
export {default as rustIcon } from './rust.svg'
export {default as jvscrptIcon } from './jvscrpt.svg'
export {default as pythonIcon } from './python.svg'
export {default as kotlin1Icon } from './kotlin1.svg'
export {default as swift1Icon } from './swift1.svg'
export {default as phpIcon } from './php.svg'

export {default as arrowDownIcon } from './arrowDownIcon.svg'
export {default as quotesIcon } from './quotes.svg'
export {default as arrowLeftV2 } from './left.svg'


export {default as vueIcon } from './vue.svg'
export {default as reactIcon } from './react.svg'
export {default as angularIcon } from './angular.svg'
export {default as javaIcon } from './java.svg'
export {default as gitIcon } from './git.svg'
export {default as gitlabIcon } from './gitlab.svg'
export {default as githubIcon } from './github.svg'

export {default as closeIcon } from './close.svg'
export {default as burgerIcon } from './burger.svg'
export {default as arrowDownGrayIcon } from './arrowDownGray.svg'
export {default as arrowRightBlueIcon } from './arrow-right.svg'
export {default as allIcon } from './techstack/All.svg'
export {default as checkIcon } from './check.svg'


export {default as logoRawIcon } from '../logo-raw.svg'
export {default as logoIcon } from '../logo.svg'
export {default as logoTextIcon } from '../logo-text.svg'
